# Generated by Django 5.0 on 2023-12-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bildens_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.TextField(blank=True, null=True, verbose_name='Who Reffered')),
                ('serviceOption', models.CharField(blank=True, choices=[('Credit Enrichment', 'Credit Enrichment'), ('Insurance', 'Insurance'), ('Taxes', 'Taxes'), ('Accounting', 'Accounting'), ('Payroll', 'Payroll'), ('Bookeeping', 'Bookkeeping'), ('Marketing', 'Marketing'), ('Loans', 'Loans')], max_length=100, null=True, verbose_name='Services')),
                ('creditEnrichment', models.TextField(blank=True, max_length=255, null=True, verbose_name='Credit Enrichment')),
                ('scores', models.TextField(blank=True, null=True, verbose_name='Scores')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('lastName', models.CharField(default='', max_length=100, verbose_name='Last Name')),
                ('dateOfBirth', models.DateField(blank=True, null=True, verbose_name='Date oF Bitrh')),
                ('numberSecurity', models.CharField(default='', max_length=100, verbose_name='Security Number')),
                ('driversLicense', models.CharField(default='', max_length=100, verbose_name='Drivers License')),
                ('marital', models.CharField(max_length=10, verbose_name='Marital Status')),
                ('email', models.EmailField(default='', max_length=100, verbose_name='Email')),
                ('codeArea', models.CharField(default='', max_length=100, verbose_name='Code Area')),
                ('phoneNumber', models.CharField(default='', max_length=100, verbose_name='Phone Number')),
                ('codeCellArea', models.CharField(default='', max_length=100, verbose_name='Code Area')),
                ('cellNumber', models.CharField(default='', max_length=100, verbose_name='Cell Number')),
                ('streetAdress', models.CharField(default='', max_length=100, verbose_name='Street Address')),
                ('aptAdress', models.CharField(default='', max_length=100, verbose_name='Apt/Address')),
                ('city', models.CharField(default='', max_length=100, verbose_name='City')),
                ('state', models.CharField(default='', max_length=100, verbose_name='State')),
                ('zipCode', models.CharField(default='', max_length=100, verbose_name='Zip Code')),
                ('moved', models.TextField(blank=True, null=True, verbose_name='Moved')),
                ('previousAdress', models.TextField(blank=True, null=True, verbose_name='Previous Address')),
                ('employer', models.TextField(default='', verbose_name='Employer')),
                ('hireDate', models.TextField(blank=True, null=True, verbose_name='Hire Date')),
                ('employeeId', models.TextField(blank=True, null=True, verbose_name='Employee ID')),
                ('work', models.TextField(default='', verbose_name='Work')),
                ('gross', models.CharField(default='', max_length=100, verbose_name='Gross')),
                ('rent', models.CharField(default='', max_length=100, verbose_name='Rent')),
                ('insurance', models.CharField(blank=True, max_length=100, null=True, verbose_name='Insurance')),
                ('loan', models.TextField(blank=True, null=True, verbose_name='Loan')),
                ('authorize', models.BooleanField(null=True, verbose_name='Authorize')),
                ('agree', models.BooleanField(null=True, verbose_name='Agree')),
                ('agreeTerms', models.BooleanField(null=True, verbose_name='Agree Terms')),
                ('imagen', models.ImageField(null=True, upload_to='images', verbose_name='Sign')),
            ],
            options={
                'verbose_name': 'Bildens_Model',
                'verbose_name_plural': 'Bildens_Model',
            },
        ),
    ]
