# Generated by Django 5.0 on 2024-01-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bildens_model',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='aptAdress',
            field=models.CharField(default='', max_length=100, verbose_name='Apt/Ste#'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='codeArea',
            field=models.CharField(default='', max_length=100, verbose_name='Area Code'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='codeCellArea',
            field=models.CharField(default='', max_length=100, verbose_name='Area Code'),
        ),
    ]
