# Generated by Django 5.0 on 2023-12-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildenmodel',
            name='lastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
