# Generated by Django 5.0 on 2023-12-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_bildenmodel_lastname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bildenmodel',
            options={},
        ),
    ]
