# Generated by Django 5.0 on 2023-12-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_bildenmodel_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BildenModel',
            new_name='Bilden_model',
        ),
        migrations.AlterModelOptions(
            name='bilden_model',
            options={'verbose_name': 'BildenModel', 'verbose_name_plural': 'BildenModel'},
        ),
    ]
