# Generated by Django 5.0 on 2024-01-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_bildens_model_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='who',
            field=models.TextField(blank=True, verbose_name='Who Reffered'),
        ),
    ]
