# Generated by Django 5.0 on 2023-12-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_rename_bildenmodel_bilden_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilden_model',
            name='serviceOption',
            field=models.CharField(blank=True, choices=[('Credit Enrichment', 'Credit Enrichment'), ('Insurance', 'Insurance'), ('Taxes', 'Taxes'), ('Accounting', 'Accounting'), ('Payroll', 'Payroll'), ('Bookeeping', 'Bookkeeping'), ('Marketing', 'Marketing'), ('Loans', 'Loans')], max_length=100, null=True, verbose_name='Options'),
        ),
        migrations.AddField(
            model_name='bilden_model',
            name='who',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
