# Generated by Django 5.0 on 2023-12-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_bilden_model_serviceoption_bilden_model_who'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilden_model',
            name='creditEnrichment',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
