# Generated by Django 5.0 on 2023-12-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_bilden_model_creditenrichment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilden_model',
            name='scores',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bilden_model',
            name='creditEnrichment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
