# Generated by Django 5.0 on 2023-12-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_bilden_model_scores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilden_model',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
