# Generated by Django 5.0 on 2023-12-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_bilden_model_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilden_model',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
