# Generated by Django 5.0 on 2023-12-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_bilden_model_driverslicense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilden_model',
            name='married',
            field=models.BooleanField(blank=True, max_length=100, null=True, verbose_name='married'),
        ),
        migrations.AddField(
            model_name='bilden_model',
            name='other',
            field=models.BooleanField(blank=True, max_length=100, null=True, verbose_name='other'),
        ),
        migrations.AddField(
            model_name='bilden_model',
            name='single',
            field=models.BooleanField(blank=True, max_length=100, null=True, verbose_name='single'),
        ),
    ]
