# Generated by Django 5.0 on 2023-12-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_bilden_model_cellnumber_bilden_model_codearea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilden_model',
            name='agree',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agree'),
        ),
        migrations.AddField(
            model_name='bilden_model',
            name='agreeTerms',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bilden_model',
            name='aptAdress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bilden_model',
            name='authorize',
            field=models.BooleanField(blank=True, max_length=100, null=True, verbose_name='Yes'),
        ),
        migrations.AddField(
            model_name='bilden_model',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bilden_model',
            name='employeeId',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bilden_model',
            name='employer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bilden_model',
            name='gross',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bilden_model',
            name='hireDate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bilden_model',
            name='insurance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bilden_model',
            name='loan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bilden_model',
            name='moved',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bilden_model',
            name='previousAdress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bilden_model',
            name='rent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bilden_model',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bilden_model',
            name='streetAdress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bilden_model',
            name='work',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bilden_model',
            name='zipCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
