# Generated by Django 5.0 on 2023-12-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_bilden_model_agree_bilden_model_agreeterms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilden_model',
            name='creditEnrichment',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Credit Enrichment'),
        ),
    ]
