# Generated by Django 5.0 on 2023-12-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_alter_bilden_model_creditenrichment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilden_model',
            name='agreeTerms',
            field=models.BooleanField(blank=True, null=True, verbose_name='agree terms'),
        ),
        migrations.AlterField(
            model_name='bilden_model',
            name='aptAdress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='apt adress'),
        ),
        migrations.AlterField(
            model_name='bilden_model',
            name='cellNumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='cell number'),
        ),
        migrations.AlterField(
            model_name='bilden_model',
            name='codeArea',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='code area'),
        ),
        migrations.AlterField(
            model_name='bilden_model',
            name='codeCellArea',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='code cell area'),
        ),
        migrations.AlterField(
            model_name='bilden_model',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='bilden_model',
            name='driversLicense',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='drivers license'),
        ),
        migrations.AlterField(
            model_name='bilden_model',
            name='lastName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='bilden_model',
            name='numberSecurity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='number security'),
        ),
        migrations.AlterField(
            model_name='bilden_model',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='bilden_model',
            name='streetAdress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='street adress'),
        ),
        migrations.AlterField(
            model_name='bilden_model',
            name='who',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
