# Generated by Django 5.0 on 2023-12-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_alter_bilden_model_agreeterms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bilden_model',
            options={'verbose_name': 'Bilden_Model', 'verbose_name_plural': 'Bilden_Model'},
        ),
    ]
