# Generated by Django 5.0 on 2023-12-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_alter_bilden_model_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bilden_model',
            new_name='Bildens_model',
        ),
        migrations.AlterModelOptions(
            name='bildens_model',
            options={'verbose_name': 'Bildens_Model', 'verbose_name_plural': 'Bildens_Model'},
        ),
    ]
