# Generated by Django 5.0 on 2023-12-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_rename_bilden_model_bildens_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='phoneNumber',
            field=models.CharField(default='123..', max_length=100, verbose_name='phone number'),
        ),
    ]
