# Generated by Django 5.0 on 2023-12-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_alter_bildens_model_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='phoneNumber',
            field=models.CharField(default='', max_length=100, verbose_name='phone number'),
        ),
    ]
