# Generated by Django 5.0 on 2023-12-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_alter_bildens_model_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='driversLicense',
            field=models.CharField(default='', max_length=100, verbose_name='drivers license'),
        ),
    ]
