# Generated by Django 5.0 on 2023-12-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_alter_bildens_model_driverslicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='agree',
            field=models.BooleanField(default=True, verbose_name='Agree'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='agreeTerms',
            field=models.BooleanField(default=True, verbose_name='agree terms'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='authorize',
            field=models.BooleanField(default=True, max_length=100, verbose_name='Yes'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='cellNumber',
            field=models.IntegerField(default=True, max_length=100, verbose_name='cell number'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='city',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='codeArea',
            field=models.IntegerField(default=True, max_length=100, verbose_name='code area'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='codeCellArea',
            field=models.IntegerField(default=True, max_length=100, verbose_name='code cell area'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='employer',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='gross',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='phoneNumber',
            field=models.IntegerField(default=True, max_length=100, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='rent',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='state',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='work',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='zipCode',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
