# Generated by Django 5.0 on 2023-12-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_alter_bildens_model_agree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='agree',
            field=models.BooleanField(default=False, max_length=100, verbose_name='Agree'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='agreeTerms',
            field=models.BooleanField(default=False, max_length=100, verbose_name='agree terms'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='authorize',
            field=models.BooleanField(default=False, max_length=100, verbose_name='Yes'),
        ),
    ]
