# Generated by Django 5.0 on 2023-12-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_alter_bildens_model_agree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='city',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='employer',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='gross',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='rent',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='state',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='work',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='zipCode',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
