# Generated by Django 5.0 on 2023-12-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_alter_bildens_model_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='cellNumber',
            field=models.IntegerField(default=False, max_length=100, verbose_name='cell number'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='codeArea',
            field=models.IntegerField(default=False, max_length=100, verbose_name='code area'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='codeCellArea',
            field=models.IntegerField(default=False, max_length=100, verbose_name='code cell area'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='phoneNumber',
            field=models.IntegerField(default=False, max_length=100, verbose_name='phone number'),
        ),
    ]
