# Generated by Django 5.0 on 2023-12-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_alter_bildens_model_agree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='driversLicense',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='drivers license'),
        ),
    ]
