# Generated by Django 5.0 on 2023-12-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0031_alter_bildens_model_driverslicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='cellNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='cell number'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='codeArea',
            field=models.IntegerField(blank=True, null=True, verbose_name='code area'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='codeCellArea',
            field=models.IntegerField(blank=True, null=True, verbose_name='code cell area'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='phoneNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='phone number'),
        ),
    ]
