# Generated by Django 5.0 on 2023-12-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_alter_bildens_model_cellnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='cellNumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='cell number'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='codeArea',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='code area'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='codeCellArea',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='code cell area'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='phone number'),
        ),
    ]
