# Generated by Django 5.0 on 2023-12-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_alter_bildens_model_cellnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
