# Generated by Django 5.0 on 2023-12-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0038_bildens_model_agree_bildens_model_agreeterms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='name',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
