# Generated by Django 5.0 on 2023-12-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0039_alter_bildens_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='lastName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
