# Generated by Django 5.0 on 2023-12-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0040_alter_bildens_model_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='lastName',
            field=models.CharField(default=True, max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='numberSecurity',
            field=models.CharField(default=True, max_length=100, verbose_name='number security'),
        ),
    ]
