# Generated by Django 5.0 on 2023-12-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0042_alter_bildens_model_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='driversLicense',
            field=models.CharField(default='', max_length=100, verbose_name='drivers license'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='numberSecurity',
            field=models.CharField(default='', max_length=100, verbose_name='number security'),
        ),
    ]
