# Generated by Django 5.0 on 2023-12-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0043_alter_bildens_model_driverslicense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
