# Generated by Django 5.0 on 2023-12-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0044_alter_bildens_model_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='aptAdress',
            field=models.CharField(default='', max_length=100, verbose_name='apt adress'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='cellNumber',
            field=models.CharField(default='', max_length=100, verbose_name='cell number'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='codeArea',
            field=models.CharField(default='', max_length=100, verbose_name='code area'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='codeCellArea',
            field=models.CharField(default='', max_length=100, verbose_name='code cell area'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='phoneNumber',
            field=models.CharField(default='', max_length=100, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='streetAdress',
            field=models.CharField(default='', max_length=100, verbose_name='street adress'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='zipCode',
            field=models.CharField(default='', max_length=100),
        ),
    ]
