# Generated by Django 5.0 on 2023-12-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0045_alter_bildens_model_aptadress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='employer',
            field=models.TextField(default=''),
        ),
    ]
