# Generated by Django 5.0 on 2023-12-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0048_alter_bildens_model_agree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='married',
            field=models.BooleanField(default=False, verbose_name='married'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='other',
            field=models.BooleanField(default=False, verbose_name='other'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='single',
            field=models.BooleanField(default=False, verbose_name='single'),
        ),
    ]
