# Generated by Django 5.0 on 2023-12-25 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0049_alter_bildens_model_married_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildens_model',
            name='marital',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
