# Generated by Django 5.0 on 2023-12-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0050_bildens_model_marital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bildens_model',
            name='married',
        ),
        migrations.RemoveField(
            model_name='bildens_model',
            name='other',
        ),
        migrations.RemoveField(
            model_name='bildens_model',
            name='single',
        ),
    ]
