# Generated by Django 5.0 on 2023-12-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0051_remove_bildens_model_married_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='agree',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='agreeTerms',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='authorize',
            field=models.BooleanField(null=True),
        ),
    ]
