# Generated by Django 5.0 on 2023-12-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0052_alter_bildens_model_agree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='aptAdress',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='cellNumber',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='codeArea',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='codeCellArea',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='driversLicense',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='numberSecurity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='phoneNumber',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='streetAdress',
            field=models.CharField(default='', max_length=100),
        ),
    ]
