# Generated by Django 5.0 on 2023-12-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0053_alter_bildens_model_aptadress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='agree',
            field=models.BooleanField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='agreeTerms',
            field=models.BooleanField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='aptAdress',
            field=models.CharField(default='', max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='authorize',
            field=models.BooleanField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='cellNumber',
            field=models.CharField(default='', max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='codeArea',
            field=models.CharField(default='', max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='codeCellArea',
            field=models.CharField(default='', max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='driversLicense',
            field=models.CharField(default='', max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='email',
            field=models.EmailField(default='', max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='employeeId',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='employer',
            field=models.TextField(default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='gross',
            field=models.CharField(default='', max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='hireDate',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='insurance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='lastName',
            field=models.CharField(default='', max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='loan',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='marital',
            field=models.CharField(max_length=10, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='moved',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='numberSecurity',
            field=models.CharField(default='', max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='phoneNumber',
            field=models.CharField(default='', max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='previousAdress',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='rent',
            field=models.CharField(default='', max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='serviceOption',
            field=models.CharField(blank=True, choices=[('Credit Enrichment', 'Credit Enrichment'), ('Insurance', 'Insurance'), ('Taxes', 'Taxes'), ('Accounting', 'Accounting'), ('Payroll', 'Payroll'), ('Bookeeping', 'Bookkeeping'), ('Marketing', 'Marketing'), ('Loans', 'Loans')], max_length=100, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='state',
            field=models.CharField(default='', max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='streetAdress',
            field=models.CharField(default='', max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='who',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='work',
            field=models.TextField(default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='zipCode',
            field=models.CharField(default='', max_length=100, verbose_name=''),
        ),
    ]
