# Generated by Django 5.0 on 2023-12-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0054_alter_bildens_model_agree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='name',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='scores',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
    ]
