# Generated by Django 5.0 on 2023-12-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0055_alter_bildens_model_name_alter_bildens_model_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='aptAdress',
            field=models.CharField(default='', max_length=100, verbose_name='Apt/Adress'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='cellNumber',
            field=models.CharField(default='', max_length=100, verbose_name='Cell Number'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='codeArea',
            field=models.CharField(default='', max_length=100, verbose_name='Code Area'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='codeCellArea',
            field=models.CharField(default='', max_length=100, verbose_name='Code Area'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='creditEnrichment',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='phoneNumber',
            field=models.CharField(default='', max_length=100, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='state',
            field=models.CharField(default='', max_length=100, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='streetAdress',
            field=models.CharField(default='', max_length=100, verbose_name='Street Adress'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='zipCode',
            field=models.CharField(default='', max_length=100, verbose_name='Zip Code'),
        ),
    ]
