# Generated by Django 5.0 on 2023-12-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0056_alter_bildens_model_aptadress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='agree',
            field=models.BooleanField(null=True, verbose_name='Yes'),
        ),
    ]
