# Generated by Django 5.0 on 2023-12-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0057_alter_bildens_model_agree'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildens_model',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='authorize',
            field=models.BooleanField(null=True, verbose_name='Yes'),
        ),
    ]
