# Generated by Django 5.0 on 2023-12-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0058_bildens_model_imagen_alter_bildens_model_authorize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imges'),
        ),
    ]
