# Generated by Django 5.0 on 2023-12-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0061_alter_bildens_model_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='who',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name=''),
        ),
    ]
