# Generated by Django 5.0 on 2023-12-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0062_alter_bildens_model_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
