# Generated by Django 5.0 on 2023-12-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0063_alter_bildens_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='who',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='who'),
        ),
    ]
