# Generated by Django 5.0 on 2023-12-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0064_alter_bildens_model_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='agree',
            field=models.BooleanField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='authorize',
            field=models.BooleanField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='name',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='who',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name=''),
        ),
    ]
