# Generated by Django 5.0 on 2023-12-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0065_alter_bildens_model_agree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='who',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
