# Generated by Django 5.0 on 2023-12-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0066_alter_bildens_model_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='agree',
            field=models.BooleanField(null=True, verbose_name='Agree'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='agreeTerms',
            field=models.BooleanField(null=True, verbose_name='Agree Terms'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='authorize',
            field=models.BooleanField(null=True, verbose_name='Authorize'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='creditEnrichment',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Credit Enrichment'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True, verbose_name='Date oF Bitrh'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='driversLicense',
            field=models.CharField(default='', max_length=100, verbose_name='Drivers License'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='email',
            field=models.EmailField(default='', max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='employeeId',
            field=models.TextField(blank=True, null=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='employer',
            field=models.TextField(default='', verbose_name='Employer'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='gross',
            field=models.CharField(default='', max_length=100, verbose_name='Gross'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='hireDate',
            field=models.TextField(blank=True, null=True, verbose_name='Hire Date'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Sign'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='insurance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Insurance'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='lastName',
            field=models.CharField(default='', max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='loan',
            field=models.TextField(blank=True, null=True, verbose_name='Loan'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='marital',
            field=models.CharField(max_length=10, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='moved',
            field=models.TextField(blank=True, null=True, verbose_name='Moved'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='numberSecurity',
            field=models.CharField(default='', max_length=100, verbose_name='Security Number'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='previousAdress',
            field=models.TextField(blank=True, null=True, verbose_name='Previous Adress'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='rent',
            field=models.CharField(default='', max_length=100, verbose_name='Rent'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='scores',
            field=models.TextField(blank=True, null=True, verbose_name='Scores'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='serviceOption',
            field=models.CharField(blank=True, choices=[('Credit Enrichment', 'Credit Enrichment'), ('Insurance', 'Insurance'), ('Taxes', 'Taxes'), ('Accounting', 'Accounting'), ('Payroll', 'Payroll'), ('Bookeeping', 'Bookkeeping'), ('Marketing', 'Marketing'), ('Loans', 'Loans')], max_length=100, null=True, verbose_name='Services'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='who',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Who Reffered'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='work',
            field=models.TextField(default='', verbose_name='Work'),
        ),
    ]
