# Generated by Django 5.0 on 2023-12-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0067_alter_bildens_model_agree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='aptAdress',
            field=models.CharField(default='', max_length=100, verbose_name='Apt/Address'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='previousAdress',
            field=models.TextField(blank=True, null=True, verbose_name='Previous Address'),
        ),
        migrations.AlterField(
            model_name='bildens_model',
            name='streetAdress',
            field=models.CharField(default='', max_length=100, verbose_name='Street Address'),
        ),
    ]
