# Generated by Django 5.0 on 2023-12-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0069_alter_bildens_model_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildens_model',
            name='who',
            field=models.TextField(blank=True, null=True, verbose_name='Who Reffered'),
        ),
    ]
